version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379:2379"
      - "4001:4001"
      - "2380:2380"
    environment:
      - ETCDCTL_API=3
    command:
      /usr/local/bin/etcd
      --name infra0
      --initial-advertise-peer-urls http://0.0.0.0:2380
      -advertise-client-urls http://0.0.0.0:2379
      -listen-client-urls http://0.0.0.0:2379
      --initial-cluster-token etcd-cluster-1
      -initial-cluster infra0=http://0.0.0.0:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-state new
    restart:
      always
  micro-api:
    command: --registry=etcd --registry_address=${REGISTRY} api --handler=http
    image: microhq/micro:latest
    depends_on:
      - etcd
    ports:
      - "8080:8080"
    restart:
      always
  micro-web:
    command: --registry=etcd --registry_address=${REGISTRY}  web
    image: microhq/micro:latest
    depends_on:
      - etcd
      - auth-api
      - task-api
      - group-api
    ports:
      - "8082:8082"
    restart:
      always
  redis:
    image: nihplod/redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    restart:
      always
  mysql:
    image: nihplod/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
    ports:
    - "3306:3306"
    restart:
      always
  auth-api:
    image: nihplod/auth-api:latest
    depends_on:
      - auth-srv
    restart:
      always
  auth-srv:
    image: nihplod/auth-srv:latest
    depends_on:
      - etcd
      - redis
      - mysql
      - nginx
    restart:
      always
  group-api:
    image: nihplod/group-api:latest
    depends_on:
      - auth-srv
      - group-srv
    restart:
      always
  group-srv:
    image: nihplod/group-srv:latest
    depends_on:
      - etcd
      - redis
      - mysql
    restart:
      always
  task-api:
    image: nihplod/task-api:latest
    depends_on:
      - auth-srv
      - group-srv
      - task-srv
    restart:
      always
  task-srv:
    image: nihplod/task-srv:latest
    depends_on:
      - etcd
      - redis
      - mysql
    restart:
      always
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx-micro.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/1_isalb.xyz_bundle.crt:/etc/nginx/isalb.crt
    - ./nginx/2_isalb.xyz.key:/etc/nginx/isalb.key
    - ./nginx/isalb.xyz.csr:/etc/nginx/isalb.csr
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "9999:9999"
    - "443:443"
    restart:
      always
