// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Avatar               *string  `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Gender               *int32   `protobuf:"varint,4,opt,name=gender" json:"gender,omitempty"`
	SelfGroupId          *int32   `protobuf:"varint,5,opt,name=self_group_id,json=selfGroupId" json:"self_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

func (m *User) GetGender() int32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *User) GetSelfGroupId() int32 {
	if m != nil && m.SelfGroupId != nil {
		return *m.SelfGroupId
	}
	return 0
}

type GetGroupRequest struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type GetGroupResponse struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	CreatorId            *string  `protobuf:"bytes,2,req,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
	Type                 *int32   `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	UpdatedAt            *string  `protobuf:"bytes,4,req,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	TaskNum              *int32   `protobuf:"varint,5,req,name=task_num,json=taskNum" json:"task_num,omitempty"`
	Users                []*User  `protobuf:"bytes,6,rep,name=users" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupResponse) Reset()         { *m = GetGroupResponse{} }
func (m *GetGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupResponse) ProtoMessage()    {}
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *GetGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupResponse.Unmarshal(m, b)
}
func (m *GetGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupResponse.Merge(m, src)
}
func (m *GetGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupResponse.Size(m)
}
func (m *GetGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupResponse proto.InternalMessageInfo

func (m *GetGroupResponse) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GetGroupResponse) GetCreatorId() string {
	if m != nil && m.CreatorId != nil {
		return *m.CreatorId
	}
	return ""
}

func (m *GetGroupResponse) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *GetGroupResponse) GetUpdatedAt() string {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return ""
}

func (m *GetGroupResponse) GetTaskNum() int32 {
	if m != nil && m.TaskNum != nil {
		return *m.TaskNum
	}
	return 0
}

func (m *GetGroupResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetGroupByUserIdRequest struct {
	UserId               *string  `protobuf:"bytes,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupByUserIdRequest) Reset()         { *m = GetGroupByUserIdRequest{} }
func (m *GetGroupByUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupByUserIdRequest) ProtoMessage()    {}
func (*GetGroupByUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *GetGroupByUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupByUserIdRequest.Unmarshal(m, b)
}
func (m *GetGroupByUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupByUserIdRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupByUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupByUserIdRequest.Merge(m, src)
}
func (m *GetGroupByUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupByUserIdRequest.Size(m)
}
func (m *GetGroupByUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupByUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupByUserIdRequest proto.InternalMessageInfo

func (m *GetGroupByUserIdRequest) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

type GetGroupByUserIdResponse struct {
	Groups               []*GetGroupByUserIdResponse_Group `protobuf:"bytes,3,rep,name=groups" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetGroupByUserIdResponse) Reset()         { *m = GetGroupByUserIdResponse{} }
func (m *GetGroupByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupByUserIdResponse) ProtoMessage()    {}
func (*GetGroupByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *GetGroupByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupByUserIdResponse.Unmarshal(m, b)
}
func (m *GetGroupByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupByUserIdResponse.Merge(m, src)
}
func (m *GetGroupByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupByUserIdResponse.Size(m)
}
func (m *GetGroupByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupByUserIdResponse proto.InternalMessageInfo

func (m *GetGroupByUserIdResponse) GetGroups() []*GetGroupByUserIdResponse_Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetGroupByUserIdResponse_Group struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	CreatorId            *string  `protobuf:"bytes,3,req,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
	Type                 *int32   `protobuf:"varint,4,req,name=type" json:"type,omitempty"`
	UpdatedAt            *string  `protobuf:"bytes,5,req,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	TaskNum              *int32   `protobuf:"varint,6,req,name=task_num,json=taskNum" json:"task_num,omitempty"`
	Users                []*User  `protobuf:"bytes,7,rep,name=users" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupByUserIdResponse_Group) Reset()         { *m = GetGroupByUserIdResponse_Group{} }
func (m *GetGroupByUserIdResponse_Group) String() string { return proto.CompactTextString(m) }
func (*GetGroupByUserIdResponse_Group) ProtoMessage()    {}
func (*GetGroupByUserIdResponse_Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4, 0}
}

func (m *GetGroupByUserIdResponse_Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupByUserIdResponse_Group.Unmarshal(m, b)
}
func (m *GetGroupByUserIdResponse_Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupByUserIdResponse_Group.Marshal(b, m, deterministic)
}
func (m *GetGroupByUserIdResponse_Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupByUserIdResponse_Group.Merge(m, src)
}
func (m *GetGroupByUserIdResponse_Group) XXX_Size() int {
	return xxx_messageInfo_GetGroupByUserIdResponse_Group.Size(m)
}
func (m *GetGroupByUserIdResponse_Group) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupByUserIdResponse_Group.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupByUserIdResponse_Group proto.InternalMessageInfo

func (m *GetGroupByUserIdResponse_Group) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GetGroupByUserIdResponse_Group) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GetGroupByUserIdResponse_Group) GetCreatorId() string {
	if m != nil && m.CreatorId != nil {
		return *m.CreatorId
	}
	return ""
}

func (m *GetGroupByUserIdResponse_Group) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *GetGroupByUserIdResponse_Group) GetUpdatedAt() string {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return ""
}

func (m *GetGroupByUserIdResponse_Group) GetTaskNum() int32 {
	if m != nil && m.TaskNum != nil {
		return *m.TaskNum
	}
	return 0
}

func (m *GetGroupByUserIdResponse_Group) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type CreateGroupRequest struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CreatorId            *string  `protobuf:"bytes,2,req,name=creator_id,json=creatorId" json:"creator_id,omitempty"`
	Type                 *int32   `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateGroupRequest) GetCreatorId() string {
	if m != nil && m.CreatorId != nil {
		return *m.CreatorId
	}
	return ""
}

func (m *CreateGroupRequest) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type CreateGroupResponse struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(m, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type UpdateGroupRequest struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(m, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UpdateGroupRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type UpdateGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupResponse) Reset()         { *m = UpdateGroupResponse{} }
func (m *UpdateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupResponse) ProtoMessage()    {}
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *UpdateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupResponse.Unmarshal(m, b)
}
func (m *UpdateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupResponse.Marshal(b, m, deterministic)
}
func (m *UpdateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupResponse.Merge(m, src)
}
func (m *UpdateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupResponse.Size(m)
}
func (m *UpdateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupResponse proto.InternalMessageInfo

type DeleteGroupRequest struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{9}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type DeleteGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupResponse) Reset()         { *m = DeleteGroupResponse{} }
func (m *DeleteGroupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupResponse) ProtoMessage()    {}
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{10}
}

func (m *DeleteGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupResponse.Unmarshal(m, b)
}
func (m *DeleteGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupResponse.Merge(m, src)
}
func (m *DeleteGroupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupResponse.Size(m)
}
func (m *DeleteGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupResponse proto.InternalMessageInfo

type UserInGroupRequest struct {
	UserId               *string  `protobuf:"bytes,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId              *int32   `protobuf:"varint,2,req,name=group_id,json=groupId" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInGroupRequest) Reset()         { *m = UserInGroupRequest{} }
func (m *UserInGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UserInGroupRequest) ProtoMessage()    {}
func (*UserInGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{11}
}

func (m *UserInGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInGroupRequest.Unmarshal(m, b)
}
func (m *UserInGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInGroupRequest.Marshal(b, m, deterministic)
}
func (m *UserInGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInGroupRequest.Merge(m, src)
}
func (m *UserInGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UserInGroupRequest.Size(m)
}
func (m *UserInGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInGroupRequest proto.InternalMessageInfo

func (m *UserInGroupRequest) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *UserInGroupRequest) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

type UserInGroupResponse struct {
	Ok                   *bool    `protobuf:"varint,1,req,name=ok" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInGroupResponse) Reset()         { *m = UserInGroupResponse{} }
func (m *UserInGroupResponse) String() string { return proto.CompactTextString(m) }
func (*UserInGroupResponse) ProtoMessage()    {}
func (*UserInGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{12}
}

func (m *UserInGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInGroupResponse.Unmarshal(m, b)
}
func (m *UserInGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInGroupResponse.Marshal(b, m, deterministic)
}
func (m *UserInGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInGroupResponse.Merge(m, src)
}
func (m *UserInGroupResponse) XXX_Size() int {
	return xxx_messageInfo_UserInGroupResponse.Size(m)
}
func (m *UserInGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInGroupResponse proto.InternalMessageInfo

func (m *UserInGroupResponse) GetOk() bool {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return false
}

type AddGroupMembersRequest struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Members              []string `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	Action               *int32   `protobuf:"varint,3,req,name=action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMembersRequest) Reset()         { *m = AddGroupMembersRequest{} }
func (m *AddGroupMembersRequest) String() string { return proto.CompactTextString(m) }
func (*AddGroupMembersRequest) ProtoMessage()    {}
func (*AddGroupMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{13}
}

func (m *AddGroupMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMembersRequest.Unmarshal(m, b)
}
func (m *AddGroupMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMembersRequest.Marshal(b, m, deterministic)
}
func (m *AddGroupMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMembersRequest.Merge(m, src)
}
func (m *AddGroupMembersRequest) XXX_Size() int {
	return xxx_messageInfo_AddGroupMembersRequest.Size(m)
}
func (m *AddGroupMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMembersRequest proto.InternalMessageInfo

func (m *AddGroupMembersRequest) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *AddGroupMembersRequest) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *AddGroupMembersRequest) GetAction() int32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

type AddGroupMembersResponse struct {
	Members              []string `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMembersResponse) Reset()         { *m = AddGroupMembersResponse{} }
func (m *AddGroupMembersResponse) String() string { return proto.CompactTextString(m) }
func (*AddGroupMembersResponse) ProtoMessage()    {}
func (*AddGroupMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{14}
}

func (m *AddGroupMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMembersResponse.Unmarshal(m, b)
}
func (m *AddGroupMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMembersResponse.Marshal(b, m, deterministic)
}
func (m *AddGroupMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMembersResponse.Merge(m, src)
}
func (m *AddGroupMembersResponse) XXX_Size() int {
	return xxx_messageInfo_AddGroupMembersResponse.Size(m)
}
func (m *AddGroupMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMembersResponse proto.InternalMessageInfo

func (m *AddGroupMembersResponse) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*GetGroupRequest)(nil), "GetGroupRequest")
	proto.RegisterType((*GetGroupResponse)(nil), "GetGroupResponse")
	proto.RegisterType((*GetGroupByUserIdRequest)(nil), "GetGroupByUserIdRequest")
	proto.RegisterType((*GetGroupByUserIdResponse)(nil), "GetGroupByUserIdResponse")
	proto.RegisterType((*GetGroupByUserIdResponse_Group)(nil), "GetGroupByUserIdResponse.Group")
	proto.RegisterType((*CreateGroupRequest)(nil), "CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "CreateGroupResponse")
	proto.RegisterType((*UpdateGroupRequest)(nil), "UpdateGroupRequest")
	proto.RegisterType((*UpdateGroupResponse)(nil), "UpdateGroupResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "DeleteGroupRequest")
	proto.RegisterType((*DeleteGroupResponse)(nil), "DeleteGroupResponse")
	proto.RegisterType((*UserInGroupRequest)(nil), "UserInGroupRequest")
	proto.RegisterType((*UserInGroupResponse)(nil), "UserInGroupResponse")
	proto.RegisterType((*AddGroupMembersRequest)(nil), "AddGroupMembersRequest")
	proto.RegisterType((*AddGroupMembersResponse)(nil), "AddGroupMembersResponse")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x7f, 0x93, 0x4c, 0x04, 0x2d, 0xeb, 0xd0, 0x6c, 0x8d, 0x10, 0x61, 0x45, 0xa5, 0x9c,
	0x16, 0x29, 0x1c, 0x88, 0xc4, 0xa9, 0xa5, 0x52, 0xc8, 0x01, 0x0e, 0x96, 0x7a, 0x29, 0x87, 0xc8,
	0xad, 0x97, 0x28, 0x4a, 0x63, 0x1b, 0x7b, 0x8d, 0xd4, 0x0b, 0x2f, 0xc0, 0xc3, 0xc0, 0x85, 0xf7,
	0x43, 0xbb, 0x5e, 0xc7, 0x76, 0x6c, 0xe7, 0xc2, 0xcd, 0x33, 0x9e, 0x6f, 0x7e, 0xbe, 0xf9, 0x66,
	0x61, 0xb8, 0x4e, 0xa2, 0x2c, 0xa6, 0x71, 0x12, 0xf1, 0x88, 0xfc, 0x04, 0xf3, 0x26, 0x65, 0x09,
	0x7a, 0x0a, 0xfa, 0x26, 0xc0, 0xda, 0x44, 0x9f, 0x0e, 0x3c, 0x7d, 0x13, 0x20, 0x04, 0x66, 0xe8,
	0xef, 0x18, 0xd6, 0xa5, 0x47, 0x7e, 0xa3, 0x33, 0xb0, 0xfd, 0x1f, 0x3e, 0xf7, 0x13, 0x6c, 0x4c,
	0xb4, 0xe9, 0xc0, 0x53, 0x96, 0xf0, 0xaf, 0x59, 0x18, 0xb0, 0x04, 0x9b, 0x13, 0x6d, 0x6a, 0x79,
	0xca, 0x42, 0x04, 0x9e, 0xa4, 0xec, 0xe1, 0xdb, 0x4a, 0xd6, 0x5b, 0x6d, 0x02, 0x6c, 0xc9, 0xdf,
	0x43, 0xe1, 0x5c, 0x08, 0xdf, 0x32, 0x20, 0xaf, 0xe1, 0x64, 0xc1, 0xb8, 0xb4, 0x3c, 0xf6, 0x3d,
	0x63, 0x29, 0xaf, 0xb4, 0x62, 0x89, 0x56, 0xc8, 0x1f, 0x0d, 0x4e, 0xcb, 0x98, 0x34, 0x8e, 0xc2,
	0x94, 0xed, 0xfb, 0xd3, 0x2a, 0xfd, 0xbd, 0x04, 0xb8, 0x4f, 0x98, 0xcf, 0xa3, 0x44, 0x14, 0xcb,
	0x3b, 0x1f, 0x28, 0xcf, 0x52, 0x8e, 0xc4, 0x1f, 0x63, 0x86, 0x0d, 0x99, 0x59, 0x7e, 0x0b, 0x48,
	0x16, 0x07, 0x3e, 0x67, 0xc1, 0xca, 0xe7, 0xd8, 0xcc, 0x21, 0xca, 0x73, 0xc9, 0xd1, 0x39, 0xf4,
	0xb9, 0x9f, 0x6e, 0x57, 0x61, 0xb6, 0xc3, 0x96, 0x84, 0xf5, 0x84, 0xfd, 0x25, 0xdb, 0xa1, 0x17,
	0x60, 0x65, 0x29, 0x4b, 0x52, 0x6c, 0x4f, 0x8c, 0xe9, 0x70, 0x66, 0x51, 0x41, 0xa3, 0x97, 0xfb,
	0xc8, 0x0c, 0xc6, 0x45, 0xc7, 0x57, 0x8f, 0xe2, 0xc7, 0x32, 0x28, 0xa6, 0x1b, 0x43, 0x4f, 0xc4,
	0xac, 0xf6, 0x6c, 0xdb, 0x99, 0xfc, 0x4f, 0x7e, 0xe9, 0x80, 0x9b, 0x20, 0x35, 0xee, 0x7b, 0xb0,
	0x25, 0x8b, 0x29, 0x36, 0x64, 0xb9, 0x57, 0xb4, 0x2b, 0x94, 0xe6, 0x3c, 0xa9, 0x70, 0xf7, 0xaf,
	0x06, 0x96, 0xf4, 0x1c, 0xd2, 0xda, 0xba, 0xe1, 0x3a, 0x83, 0x46, 0x17, 0x83, 0x66, 0x27, 0x83,
	0xd6, 0x31, 0x06, 0xed, 0x0e, 0x06, 0x7b, 0x2d, 0x0c, 0x7e, 0x05, 0xf4, 0x51, 0xd4, 0x65, 0x35,
	0x69, 0x94, 0x5b, 0xd7, 0xfe, 0x63, 0xeb, 0xe4, 0x02, 0x9c, 0x5a, 0x72, 0x45, 0xf2, 0xa1, 0xf0,
	0xe6, 0x80, 0x6e, 0xe4, 0x20, 0xc7, 0xe4, 0x59, 0xe1, 0x71, 0xdf, 0x13, 0x79, 0x0e, 0x4e, 0x0d,
	0x99, 0x17, 0x20, 0x6f, 0x00, 0x5d, 0xb3, 0x07, 0x76, 0x3c, 0xa1, 0x00, 0xd7, 0xa2, 0x14, 0xf8,
	0x13, 0x20, 0xb9, 0xe9, 0xb0, 0x06, 0xee, 0x92, 0x93, 0x20, 0x7e, 0x7f, 0x77, 0x7a, 0x4e, 0xfc,
	0x5a, 0xdd, 0xdc, 0x05, 0x38, 0xb5, 0x4c, 0xe5, 0xf8, 0xd1, 0x56, 0x66, 0xe9, 0x7b, 0x7a, 0xb4,
	0x25, 0xb7, 0x70, 0x76, 0x19, 0x04, 0x32, 0xe6, 0x33, 0xdb, 0xdd, 0xb1, 0x24, 0xed, 0xa2, 0x00,
	0x43, 0x6f, 0x97, 0x47, 0x60, 0x7d, 0x62, 0x4c, 0x07, 0x5e, 0x61, 0xca, 0x27, 0xe3, 0x9e, 0x6f,
	0xa2, 0x50, 0xf1, 0xaf, 0x2c, 0xf2, 0x0e, 0xc6, 0x8d, 0xdc, 0xaa, 0x8d, 0x4a, 0x32, 0xad, 0x96,
	0x6c, 0xf6, 0xdb, 0x28, 0xb4, 0xfc, 0x16, 0xfa, 0x85, 0xfe, 0xd1, 0x29, 0x3d, 0x78, 0x40, 0xdc,
	0x67, 0xb4, 0xf1, 0x5c, 0x2c, 0xca, 0x27, 0xa4, 0x38, 0x18, 0x84, 0x69, 0xc7, 0x8d, 0xba, 0xe7,
	0x9d, 0xd7, 0x85, 0xe6, 0x30, 0xac, 0x48, 0x07, 0x39, 0xb4, 0xa9, 0x52, 0x77, 0x44, 0xdb, 0xd4,
	0x35, 0x87, 0x61, 0x45, 0x13, 0xc8, 0xa1, 0x4d, 0x6d, 0xb9, 0x23, 0xda, 0x22, 0x1b, 0x81, 0xac,
	0x08, 0x02, 0x39, 0xb4, 0x29, 0x22, 0x77, 0x44, 0x5b, 0x34, 0x23, 0x6b, 0x96, 0x9b, 0x16, 0x35,
	0x1b, 0x0a, 0x12, 0x35, 0x5b, 0xc4, 0x70, 0x0d, 0x27, 0x07, 0x0b, 0x42, 0x63, 0xda, 0x2e, 0x07,
	0x17, 0xd3, 0x8e, 0x5d, 0x5e, 0xd9, 0xb7, 0x26, 0xfd, 0x10, 0xdf, 0xfd, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xb2, 0x29, 0x8d, 0xbb, 0x73, 0x06, 0x00, 0x00,
}
