// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: group.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Group service

type GroupService interface {
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...client.CallOption) (*GetGroupResponse, error)
}

type groupService struct {
	c    client.Client
	name string
}

func NewGroupService(name string, c client.Client) GroupService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "group"
	}
	return &groupService{
		c:    c,
		name: name,
	}
}

func (c *groupService) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...client.CallOption) (*GetGroupResponse, error) {
	req := c.c.NewRequest(c.name, "Group.GetGroup", in)
	out := new(GetGroupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Group service

type GroupHandler interface {
	GetGroup(context.Context, *GetGroupRequest, *GetGroupResponse) error
}

func RegisterGroupHandler(s server.Server, hdlr GroupHandler, opts ...server.HandlerOption) error {
	type group interface {
		GetGroup(ctx context.Context, in *GetGroupRequest, out *GetGroupResponse) error
	}
	type Group struct {
		group
	}
	h := &groupHandler{hdlr}
	return s.Handle(s.NewHandler(&Group{h}, opts...))
}

type groupHandler struct {
	GroupHandler
}

func (h *groupHandler) GetGroup(ctx context.Context, in *GetGroupRequest, out *GetGroupResponse) error {
	return h.GroupHandler.GetGroup(ctx, in, out)
}
