// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	// insert user id
	OnLogin(ctx context.Context, in *OnLoginRequest, opts ...client.CallOption) (*OnLoginResponse, error)
	// update user name gender, create self_group
	AfterLogin(ctx context.Context, in *AfterLoginRequest, opts ...client.CallOption) (*AfterLoginResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error)
	CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...client.CallOption) (*CheckAuthResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pb"
	}
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) OnLogin(ctx context.Context, in *OnLoginRequest, opts ...client.CallOption) (*OnLoginResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.onLogin", in)
	out := new(OnLoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) AfterLogin(ctx context.Context, in *AfterLoginRequest, opts ...client.CallOption) (*AfterLoginResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.afterLogin", in)
	out := new(AfterLoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetUser(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.getUser", in)
	out := new(GetUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...client.CallOption) (*CheckAuthResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.checkAuth", in)
	out := new(CheckAuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	// insert user id
	OnLogin(context.Context, *OnLoginRequest, *OnLoginResponse) error
	// update user name gender, create self_group
	AfterLogin(context.Context, *AfterLoginRequest, *AfterLoginResponse) error
	GetUser(context.Context, *GetUserRequest, *GetUserResponse) error
	CheckAuth(context.Context, *CheckAuthRequest, *CheckAuthResponse) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		OnLogin(ctx context.Context, in *OnLoginRequest, out *OnLoginResponse) error
		AfterLogin(ctx context.Context, in *AfterLoginRequest, out *AfterLoginResponse) error
		GetUser(ctx context.Context, in *GetUserRequest, out *GetUserResponse) error
		CheckAuth(ctx context.Context, in *CheckAuthRequest, out *CheckAuthResponse) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) OnLogin(ctx context.Context, in *OnLoginRequest, out *OnLoginResponse) error {
	return h.AuthHandler.OnLogin(ctx, in, out)
}

func (h *authHandler) AfterLogin(ctx context.Context, in *AfterLoginRequest, out *AfterLoginResponse) error {
	return h.AuthHandler.AfterLogin(ctx, in, out)
}

func (h *authHandler) GetUser(ctx context.Context, in *GetUserRequest, out *GetUserResponse) error {
	return h.AuthHandler.GetUser(ctx, in, out)
}

func (h *authHandler) CheckAuth(ctx context.Context, in *CheckAuthRequest, out *CheckAuthResponse) error {
	return h.AuthHandler.CheckAuth(ctx, in, out)
}
