// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OnLoginRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnLoginRequest) Reset()         { *m = OnLoginRequest{} }
func (m *OnLoginRequest) String() string { return proto.CompactTextString(m) }
func (*OnLoginRequest) ProtoMessage()    {}
func (*OnLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *OnLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnLoginRequest.Unmarshal(m, b)
}
func (m *OnLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnLoginRequest.Marshal(b, m, deterministic)
}
func (m *OnLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnLoginRequest.Merge(m, src)
}
func (m *OnLoginRequest) XXX_Size() int {
	return xxx_messageInfo_OnLoginRequest.Size(m)
}
func (m *OnLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnLoginRequest proto.InternalMessageInfo

func (m *OnLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type OnLoginResponse struct {
	// encrypied openid
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// pass session id for all requests
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnLoginResponse) Reset()         { *m = OnLoginResponse{} }
func (m *OnLoginResponse) String() string { return proto.CompactTextString(m) }
func (*OnLoginResponse) ProtoMessage()    {}
func (*OnLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *OnLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnLoginResponse.Unmarshal(m, b)
}
func (m *OnLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnLoginResponse.Marshal(b, m, deterministic)
}
func (m *OnLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnLoginResponse.Merge(m, src)
}
func (m *OnLoginResponse) XXX_Size() int {
	return xxx_messageInfo_OnLoginResponse.Size(m)
}
func (m *OnLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnLoginResponse proto.InternalMessageInfo

func (m *OnLoginResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OnLoginResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type AfterLoginRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 0 male 1 female
	Gender               uint32   `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Sid                  string   `protobuf:"bytes,4,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AfterLoginRequest) Reset()         { *m = AfterLoginRequest{} }
func (m *AfterLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AfterLoginRequest) ProtoMessage()    {}
func (*AfterLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *AfterLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AfterLoginRequest.Unmarshal(m, b)
}
func (m *AfterLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AfterLoginRequest.Marshal(b, m, deterministic)
}
func (m *AfterLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AfterLoginRequest.Merge(m, src)
}
func (m *AfterLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AfterLoginRequest.Size(m)
}
func (m *AfterLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AfterLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AfterLoginRequest proto.InternalMessageInfo

func (m *AfterLoginRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AfterLoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AfterLoginRequest) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *AfterLoginRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type AfterLoginResponse struct {
	Err                  int32    `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AfterLoginResponse) Reset()         { *m = AfterLoginResponse{} }
func (m *AfterLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AfterLoginResponse) ProtoMessage()    {}
func (*AfterLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AfterLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AfterLoginResponse.Unmarshal(m, b)
}
func (m *AfterLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AfterLoginResponse.Marshal(b, m, deterministic)
}
func (m *AfterLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AfterLoginResponse.Merge(m, src)
}
func (m *AfterLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AfterLoginResponse.Size(m)
}
func (m *AfterLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AfterLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AfterLoginResponse proto.InternalMessageInfo

func (m *AfterLoginResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender               uint32   `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type CheckAuthRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthRequest) Reset()         { *m = CheckAuthRequest{} }
func (m *CheckAuthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAuthRequest) ProtoMessage()    {}
func (*CheckAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *CheckAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthRequest.Unmarshal(m, b)
}
func (m *CheckAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthRequest.Marshal(b, m, deterministic)
}
func (m *CheckAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthRequest.Merge(m, src)
}
func (m *CheckAuthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAuthRequest.Size(m)
}
func (m *CheckAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthRequest proto.InternalMessageInfo

func (m *CheckAuthRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CheckAuthRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type CheckAuthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthResponse) Reset()         { *m = CheckAuthResponse{} }
func (m *CheckAuthResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAuthResponse) ProtoMessage()    {}
func (*CheckAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *CheckAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthResponse.Unmarshal(m, b)
}
func (m *CheckAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthResponse.Marshal(b, m, deterministic)
}
func (m *CheckAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthResponse.Merge(m, src)
}
func (m *CheckAuthResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAuthResponse.Size(m)
}
func (m *CheckAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthResponse proto.InternalMessageInfo

func (m *CheckAuthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*OnLoginRequest)(nil), "pb.OnLoginRequest")
	proto.RegisterType((*OnLoginResponse)(nil), "pb.OnLoginResponse")
	proto.RegisterType((*AfterLoginRequest)(nil), "pb.AfterLoginRequest")
	proto.RegisterType((*AfterLoginResponse)(nil), "pb.AfterLoginResponse")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "pb.GetUserResponse")
	proto.RegisterType((*CheckAuthRequest)(nil), "pb.CheckAuthRequest")
	proto.RegisterType((*CheckAuthResponse)(nil), "pb.CheckAuthResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x4b, 0x05, 0x99, 0x44, 0x3e, 0x46, 0x21, 0x84, 0x13, 0x59, 0x8d, 0xe1, 0xd4, 0x83,
	0x70, 0xd2, 0x70, 0x40, 0x0f, 0x5e, 0x4c, 0x4c, 0x9a, 0x78, 0xf1, 0xd6, 0xd2, 0x91, 0x36, 0x8d,
	0xdd, 0xba, 0xdd, 0xfe, 0x6c, 0xff, 0x83, 0xe9, 0xf6, 0x83, 0xb6, 0xc8, 0x6d, 0xfa, 0xf2, 0xde,
	0xbc, 0xb7, 0x6f, 0x0a, 0xe0, 0xa4, 0xca, 0xb7, 0x62, 0x29, 0x94, 0x40, 0x16, 0xbb, 0xfc, 0x0e,
	0x86, 0xef, 0xd1, 0x9b, 0x38, 0x04, 0x91, 0x4d, 0x3f, 0x29, 0x25, 0x0a, 0x11, 0xcc, 0xbd, 0xf0,
	0x68, 0x6e, 0x2c, 0x8d, 0xd5, 0xc0, 0xd6, 0x33, 0x5f, 0xc3, 0xa8, 0x62, 0x25, 0xb1, 0x88, 0x12,
	0xc2, 0x21, 0xb0, 0xc0, 0x2b, 0x48, 0x2c, 0xf0, 0x70, 0x0c, 0xdd, 0x24, 0xf0, 0xe6, 0x4c, 0x03,
	0xd9, 0xc8, 0x1d, 0x98, 0xec, 0xbe, 0x14, 0xc9, 0xc6, 0xf6, 0xb6, 0x0c, 0xc1, 0x8c, 0x9c, 0x6f,
	0x2a, 0x74, 0x7a, 0xc6, 0x19, 0xf4, 0x0e, 0x14, 0x79, 0x24, 0xe7, 0xdd, 0xa5, 0xb1, 0xba, 0xb2,
	0x8b, 0xaf, 0xd2, 0xc2, 0x3c, 0x5a, 0xdc, 0x03, 0xd6, 0x2d, 0x8a, 0x68, 0x63, 0xe8, 0x92, 0x94,
	0xda, 0xe4, 0xc2, 0xce, 0x46, 0xbe, 0x84, 0xe1, 0x2b, 0xa9, 0x8f, 0x84, 0xe4, 0x99, 0x1c, 0x7c,
	0x0b, 0xa3, 0x8a, 0x51, 0xac, 0x29, 0xa3, 0x19, 0xff, 0x46, 0x63, 0xf5, 0x68, 0x7c, 0x03, 0xe3,
	0x17, 0x9f, 0xf6, 0xe1, 0x2e, 0x55, 0xfe, 0xb9, 0xa7, 0x9e, 0x36, 0x74, 0x0b, 0x93, 0x9a, 0xea,
	0x58, 0xac, 0x08, 0xb5, 0xec, 0xd2, 0x66, 0x22, 0x7c, 0xf8, 0x35, 0xc0, 0xcc, 0x08, 0xb8, 0x81,
	0xbe, 0xc8, 0x8f, 0x80, 0x68, 0xc5, 0xae, 0xd5, 0xbc, 0xdb, 0xe2, 0xba, 0x81, 0xe5, 0xcb, 0x78,
	0x07, 0xb7, 0x00, 0x4e, 0x55, 0x11, 0x4e, 0x33, 0xd2, 0xc9, 0x55, 0x16, 0xb3, 0x36, 0x5c, 0xc9,
	0x37, 0xd0, 0x3f, 0xe4, 0xbd, 0xe4, 0xa6, 0xcd, 0x1a, 0x73, 0xd3, 0x56, 0x71, 0xbc, 0x83, 0x8f,
	0x30, 0xd8, 0x97, 0x0f, 0xc3, 0x9b, 0x8c, 0xd3, 0x6e, 0x67, 0x31, 0x6d, 0xa1, 0xa5, 0xf6, 0xb9,
	0xf7, 0x69, 0x5a, 0x4f, 0xb1, 0xeb, 0xf6, 0xf4, 0x4f, 0xba, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0xcc, 0xf7, 0x47, 0xb2, 0x02, 0x00, 0x00,
}
