// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskMeta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Done                 bool     `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	GroupId              uint32   `protobuf:"varint,4,opt,name=groupId,proto3" json:"groupId,omitempty"`
	PublisherId          string   `protobuf:"bytes,5,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	LeaderId             string   `protobuf:"bytes,6,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	StartDate            string   `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Readonly             bool     `protobuf:"varint,9,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Description          string   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskMeta) Reset()         { *m = TaskMeta{} }
func (m *TaskMeta) String() string { return proto.CompactTextString(m) }
func (*TaskMeta) ProtoMessage()    {}
func (*TaskMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *TaskMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskMeta.Unmarshal(m, b)
}
func (m *TaskMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskMeta.Marshal(b, m, deterministic)
}
func (m *TaskMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskMeta.Merge(m, src)
}
func (m *TaskMeta) XXX_Size() int {
	return xxx_messageInfo_TaskMeta.Size(m)
}
func (m *TaskMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TaskMeta proto.InternalMessageInfo

func (m *TaskMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskMeta) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TaskMeta) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *TaskMeta) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *TaskMeta) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *TaskMeta) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *TaskMeta) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *TaskMeta) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *TaskMeta) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

func (m *TaskMeta) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetTaskMetaRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskMetaRequest) Reset()         { *m = GetTaskMetaRequest{} }
func (m *GetTaskMetaRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskMetaRequest) ProtoMessage()    {}
func (*GetTaskMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *GetTaskMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskMetaRequest.Unmarshal(m, b)
}
func (m *GetTaskMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskMetaRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskMetaRequest.Merge(m, src)
}
func (m *GetTaskMetaRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskMetaRequest.Size(m)
}
func (m *GetTaskMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskMetaRequest proto.InternalMessageInfo

func (m *GetTaskMetaRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetTaskMetaResponse struct {
	Meta                 *TaskMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTaskMetaResponse) Reset()         { *m = GetTaskMetaResponse{} }
func (m *GetTaskMetaResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskMetaResponse) ProtoMessage()    {}
func (*GetTaskMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *GetTaskMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskMetaResponse.Unmarshal(m, b)
}
func (m *GetTaskMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskMetaResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskMetaResponse.Merge(m, src)
}
func (m *GetTaskMetaResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskMetaResponse.Size(m)
}
func (m *GetTaskMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskMetaResponse proto.InternalMessageInfo

func (m *GetTaskMetaResponse) GetMeta() *TaskMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type GetTaskPeopleRequset struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskPeopleRequset) Reset()         { *m = GetTaskPeopleRequset{} }
func (m *GetTaskPeopleRequset) String() string { return proto.CompactTextString(m) }
func (*GetTaskPeopleRequset) ProtoMessage()    {}
func (*GetTaskPeopleRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *GetTaskPeopleRequset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskPeopleRequset.Unmarshal(m, b)
}
func (m *GetTaskPeopleRequset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskPeopleRequset.Marshal(b, m, deterministic)
}
func (m *GetTaskPeopleRequset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskPeopleRequset.Merge(m, src)
}
func (m *GetTaskPeopleRequset) XXX_Size() int {
	return xxx_messageInfo_GetTaskPeopleRequset.Size(m)
}
func (m *GetTaskPeopleRequset) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskPeopleRequset.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskPeopleRequset proto.InternalMessageInfo

func (m *GetTaskPeopleRequset) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetTaskPeopleResponse struct {
	Workers              []*GetTaskPeopleResponse_User `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetTaskPeopleResponse) Reset()         { *m = GetTaskPeopleResponse{} }
func (m *GetTaskPeopleResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskPeopleResponse) ProtoMessage()    {}
func (*GetTaskPeopleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *GetTaskPeopleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskPeopleResponse.Unmarshal(m, b)
}
func (m *GetTaskPeopleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskPeopleResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskPeopleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskPeopleResponse.Merge(m, src)
}
func (m *GetTaskPeopleResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskPeopleResponse.Size(m)
}
func (m *GetTaskPeopleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskPeopleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskPeopleResponse proto.InternalMessageInfo

func (m *GetTaskPeopleResponse) GetWorkers() []*GetTaskPeopleResponse_User {
	if m != nil {
		return m.Workers
	}
	return nil
}

type GetTaskPeopleResponse_User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskPeopleResponse_User) Reset()         { *m = GetTaskPeopleResponse_User{} }
func (m *GetTaskPeopleResponse_User) String() string { return proto.CompactTextString(m) }
func (*GetTaskPeopleResponse_User) ProtoMessage()    {}
func (*GetTaskPeopleResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4, 0}
}

func (m *GetTaskPeopleResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskPeopleResponse_User.Unmarshal(m, b)
}
func (m *GetTaskPeopleResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskPeopleResponse_User.Marshal(b, m, deterministic)
}
func (m *GetTaskPeopleResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskPeopleResponse_User.Merge(m, src)
}
func (m *GetTaskPeopleResponse_User) XXX_Size() int {
	return xxx_messageInfo_GetTaskPeopleResponse_User.Size(m)
}
func (m *GetTaskPeopleResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskPeopleResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskPeopleResponse_User proto.InternalMessageInfo

func (m *GetTaskPeopleResponse_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetTaskPeopleResponse_User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTaskMetaByGroupIdRequest struct {
	GroupId              uint32   `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskMetaByGroupIdRequest) Reset()         { *m = GetTaskMetaByGroupIdRequest{} }
func (m *GetTaskMetaByGroupIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskMetaByGroupIdRequest) ProtoMessage()    {}
func (*GetTaskMetaByGroupIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *GetTaskMetaByGroupIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskMetaByGroupIdRequest.Unmarshal(m, b)
}
func (m *GetTaskMetaByGroupIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskMetaByGroupIdRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskMetaByGroupIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskMetaByGroupIdRequest.Merge(m, src)
}
func (m *GetTaskMetaByGroupIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskMetaByGroupIdRequest.Size(m)
}
func (m *GetTaskMetaByGroupIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskMetaByGroupIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskMetaByGroupIdRequest proto.InternalMessageInfo

func (m *GetTaskMetaByGroupIdRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type GetTaskMetaByGroupIdResponse struct {
	Metas                []*TaskMeta `protobuf:"bytes,1,rep,name=metas,proto3" json:"metas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTaskMetaByGroupIdResponse) Reset()         { *m = GetTaskMetaByGroupIdResponse{} }
func (m *GetTaskMetaByGroupIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskMetaByGroupIdResponse) ProtoMessage()    {}
func (*GetTaskMetaByGroupIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *GetTaskMetaByGroupIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskMetaByGroupIdResponse.Unmarshal(m, b)
}
func (m *GetTaskMetaByGroupIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskMetaByGroupIdResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskMetaByGroupIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskMetaByGroupIdResponse.Merge(m, src)
}
func (m *GetTaskMetaByGroupIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskMetaByGroupIdResponse.Size(m)
}
func (m *GetTaskMetaByGroupIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskMetaByGroupIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskMetaByGroupIdResponse proto.InternalMessageInfo

func (m *GetTaskMetaByGroupIdResponse) GetMetas() []*TaskMeta {
	if m != nil {
		return m.Metas
	}
	return nil
}

type CreateTaskRequest struct {
	GroupId              int32    `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds              []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	LeaderId             string   `protobuf:"bytes,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	StartDate            string   `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	PublisherId          string   `protobuf:"bytes,9,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	Readonly             bool     `protobuf:"varint,10,opt,name=readonly,proto3" json:"readonly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (m *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(m, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *CreateTaskRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *CreateTaskRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTaskRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateTaskRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *CreateTaskRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CreateTaskRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *CreateTaskRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateTaskRequest) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *CreateTaskRequest) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

type CreateTaskResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskResponse) Reset()         { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()    {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *CreateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskResponse.Unmarshal(m, b)
}
func (m *CreateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskResponse.Marshal(b, m, deterministic)
}
func (m *CreateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskResponse.Merge(m, src)
}
func (m *CreateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTaskResponse.Size(m)
}
func (m *CreateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskResponse proto.InternalMessageInfo

func (m *CreateTaskResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateTaskMetaRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate            string   `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Readonly             bool     `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskMetaRequest) Reset()         { *m = UpdateTaskMetaRequest{} }
func (m *UpdateTaskMetaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskMetaRequest) ProtoMessage()    {}
func (*UpdateTaskMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{9}
}

func (m *UpdateTaskMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskMetaRequest.Unmarshal(m, b)
}
func (m *UpdateTaskMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskMetaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskMetaRequest.Merge(m, src)
}
func (m *UpdateTaskMetaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskMetaRequest.Size(m)
}
func (m *UpdateTaskMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskMetaRequest proto.InternalMessageInfo

func (m *UpdateTaskMetaRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTaskMetaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTaskMetaRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *UpdateTaskMetaRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *UpdateTaskMetaRequest) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

func (m *UpdateTaskMetaRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateTaskMetaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskMetaResponse) Reset()         { *m = UpdateTaskMetaResponse{} }
func (m *UpdateTaskMetaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskMetaResponse) ProtoMessage()    {}
func (*UpdateTaskMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{10}
}

func (m *UpdateTaskMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskMetaResponse.Unmarshal(m, b)
}
func (m *UpdateTaskMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskMetaResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskMetaResponse.Merge(m, src)
}
func (m *UpdateTaskMetaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskMetaResponse.Size(m)
}
func (m *UpdateTaskMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskMetaResponse proto.InternalMessageInfo

type DeleteTaskRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{11}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskResponse) Reset()         { *m = DeleteTaskResponse{} }
func (m *DeleteTaskResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskResponse) ProtoMessage()    {}
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{12}
}

func (m *DeleteTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskResponse.Unmarshal(m, b)
}
func (m *DeleteTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskResponse.Merge(m, src)
}
func (m *DeleteTaskResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskResponse.Size(m)
}
func (m *DeleteTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskResponse proto.InternalMessageInfo

type UserInTaskRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId               uint32   `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInTaskRequest) Reset()         { *m = UserInTaskRequest{} }
func (m *UserInTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UserInTaskRequest) ProtoMessage()    {}
func (*UserInTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{13}
}

func (m *UserInTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInTaskRequest.Unmarshal(m, b)
}
func (m *UserInTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInTaskRequest.Marshal(b, m, deterministic)
}
func (m *UserInTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInTaskRequest.Merge(m, src)
}
func (m *UserInTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UserInTaskRequest.Size(m)
}
func (m *UserInTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInTaskRequest proto.InternalMessageInfo

func (m *UserInTaskRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInTaskRequest) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type UserInTaskResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInTaskResponse) Reset()         { *m = UserInTaskResponse{} }
func (m *UserInTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UserInTaskResponse) ProtoMessage()    {}
func (*UserInTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{14}
}

func (m *UserInTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInTaskResponse.Unmarshal(m, b)
}
func (m *UserInTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInTaskResponse.Marshal(b, m, deterministic)
}
func (m *UserInTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInTaskResponse.Merge(m, src)
}
func (m *UserInTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UserInTaskResponse.Size(m)
}
func (m *UserInTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInTaskResponse proto.InternalMessageInfo

func (m *UserInTaskResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*TaskMeta)(nil), "TaskMeta")
	proto.RegisterType((*GetTaskMetaRequest)(nil), "GetTaskMetaRequest")
	proto.RegisterType((*GetTaskMetaResponse)(nil), "GetTaskMetaResponse")
	proto.RegisterType((*GetTaskPeopleRequset)(nil), "GetTaskPeopleRequset")
	proto.RegisterType((*GetTaskPeopleResponse)(nil), "GetTaskPeopleResponse")
	proto.RegisterType((*GetTaskPeopleResponse_User)(nil), "GetTaskPeopleResponse.User")
	proto.RegisterType((*GetTaskMetaByGroupIdRequest)(nil), "GetTaskMetaByGroupIdRequest")
	proto.RegisterType((*GetTaskMetaByGroupIdResponse)(nil), "GetTaskMetaByGroupIdResponse")
	proto.RegisterType((*CreateTaskRequest)(nil), "CreateTaskRequest")
	proto.RegisterType((*CreateTaskResponse)(nil), "CreateTaskResponse")
	proto.RegisterType((*UpdateTaskMetaRequest)(nil), "UpdateTaskMetaRequest")
	proto.RegisterType((*UpdateTaskMetaResponse)(nil), "UpdateTaskMetaResponse")
	proto.RegisterType((*DeleteTaskRequest)(nil), "DeleteTaskRequest")
	proto.RegisterType((*DeleteTaskResponse)(nil), "DeleteTaskResponse")
	proto.RegisterType((*UserInTaskRequest)(nil), "UserInTaskRequest")
	proto.RegisterType((*UserInTaskResponse)(nil), "UserInTaskResponse")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0x15, 0xc7, 0x71, 0xec, 0xc9, 0xd3, 0x4a, 0xdd, 0xf4, 0x65, 0xeb, 0xb6, 0x7a, 0x82,
	0x41, 0x28, 0xe2, 0xb0, 0x87, 0x42, 0xa5, 0x4a, 0x1c, 0x2a, 0x4a, 0x51, 0x95, 0x03, 0x12, 0x32,
	0xf4, 0xc2, 0xa5, 0x72, 0xd9, 0x11, 0x44, 0x71, 0x6d, 0xe3, 0xdd, 0x08, 0x95, 0x4f, 0xc2, 0x57,
	0xe0, 0xcc, 0x9d, 0xcf, 0x86, 0x76, 0xed, 0xf8, 0xbd, 0xbe, 0x79, 0x67, 0x66, 0x67, 0x77, 0x67,
	0x7e, 0xff, 0x31, 0x80, 0x0c, 0xc4, 0x8a, 0x25, 0x69, 0x2c, 0x63, 0xef, 0x97, 0x01, 0xf6, 0xa7,
	0x40, 0xac, 0xde, 0xa3, 0x0c, 0x08, 0x01, 0x33, 0x0a, 0xee, 0x91, 0x0e, 0x66, 0x83, 0xb9, 0xe3,
	0xeb, 0x6f, 0x65, 0x93, 0x0f, 0x09, 0x52, 0x63, 0x36, 0x98, 0x6f, 0xf9, 0xfa, 0x5b, 0xd9, 0x78,
	0x1c, 0x21, 0x1d, 0xce, 0x06, 0x73, 0xdb, 0xd7, 0xdf, 0x84, 0xc2, 0xf8, 0x6b, 0x1a, 0xaf, 0x93,
	0x05, 0xa7, 0xa6, 0x0e, 0xdd, 0x2c, 0xc9, 0x13, 0xf8, 0x2f, 0x59, 0xdf, 0x85, 0x4b, 0xf1, 0x0d,
	0xd3, 0xdb, 0x25, 0xa7, 0x23, 0x9d, 0x7d, 0x52, 0xd8, 0x16, 0x9c, 0x1c, 0x81, 0x13, 0x62, 0xc0,
	0x33, 0xbf, 0xa5, 0xfd, 0x76, 0x66, 0x58, 0x70, 0x72, 0x02, 0x20, 0x64, 0x90, 0xca, 0x5b, 0x1e,
	0x48, 0xa4, 0x63, 0xed, 0x75, 0xb4, 0xe5, 0x2a, 0x90, 0x48, 0x0e, 0xc1, 0xc6, 0x88, 0x67, 0x4e,
	0x5b, 0x3b, 0xc7, 0x18, 0x71, 0xed, 0x72, 0xc1, 0x4e, 0x31, 0xe0, 0x71, 0x14, 0x3e, 0x50, 0x47,
	0xdf, 0xb5, 0x58, 0x93, 0x19, 0x4c, 0x38, 0x8a, 0x2f, 0xe9, 0x32, 0x91, 0xcb, 0x38, 0xa2, 0x90,
	0x5d, 0xaa, 0x62, 0xf2, 0x9e, 0x01, 0xb9, 0x46, 0xb9, 0x29, 0x8e, 0x8f, 0xdf, 0xd7, 0x28, 0x24,
	0xd9, 0x06, 0x63, 0xc9, 0x75, 0x85, 0xb6, 0x7c, 0x63, 0xc9, 0xbd, 0x57, 0x30, 0xad, 0x45, 0x89,
	0x24, 0x8e, 0x04, 0x92, 0x13, 0x30, 0xef, 0x51, 0x06, 0x3a, 0x70, 0x72, 0xea, 0xb0, 0x22, 0x40,
	0x9b, 0xbd, 0xe7, 0xb0, 0x9b, 0xef, 0xfa, 0x80, 0x71, 0x12, 0xa2, 0xca, 0x2e, 0xb0, 0x9d, 0xfd,
	0x27, 0xec, 0x35, 0xe2, 0xf2, 0xfc, 0x67, 0x30, 0xfe, 0x11, 0xa7, 0x2b, 0x4c, 0x05, 0x1d, 0xcc,
	0x86, 0xf3, 0xc9, 0xe9, 0x11, 0xeb, 0x0c, 0x64, 0x37, 0x02, 0x53, 0x7f, 0x13, 0xeb, 0xbe, 0x00,
	0x53, 0x19, 0x2a, 0xe7, 0x38, 0xea, 0x9c, 0xa2, 0xf3, 0x46, 0xd9, 0x79, 0xef, 0x1c, 0x8e, 0x2a,
	0x2f, 0xbb, 0x7c, 0xb8, 0xce, 0xfa, 0xb9, 0x29, 0xc4, 0x21, 0xd8, 0xba, 0xc3, 0xb7, 0xc5, 0x85,
	0x37, 0x1d, 0xf7, 0x2e, 0xe0, 0xb8, 0x7b, 0x67, 0x7e, 0xf9, 0xff, 0x61, 0xa4, 0xaa, 0xb0, 0xb9,
	0x7a, 0xa5, 0x3a, 0x99, 0xdd, 0xfb, 0x6d, 0xc0, 0xce, 0xdb, 0x14, 0x03, 0x89, 0xca, 0xf3, 0xd8,
	0x89, 0xa3, 0x92, 0xb1, 0x43, 0xb0, 0xd7, 0x42, 0xe3, 0x23, 0xa8, 0x31, 0x1b, 0x2a, 0x08, 0xd4,
	0x7a, 0xc1, 0x45, 0xf1, 0xb4, 0x61, 0x07, 0xd4, 0xa6, 0xce, 0x92, 0x41, 0x5d, 0x63, 0x70, 0xd4,
	0xcb, 0xa0, 0xd5, 0xc7, 0xe0, 0xb8, 0xce, 0x60, 0x83, 0x33, 0xbb, 0xc5, 0x59, 0x4b, 0x1f, 0x4e,
	0x5b, 0x1f, 0x55, 0x90, 0xa1, 0x0e, 0xb2, 0xc2, 0xb4, 0x5a, 0xaa, 0xbc, 0xc4, 0x4d, 0x90, 0xfe,
	0x0c, 0x60, 0xef, 0x26, 0xe1, 0x79, 0x58, 0x0f, 0xd0, 0x5d, 0x28, 0x34, 0x9e, 0x3f, 0xec, 0x7b,
	0xbe, 0xf9, 0xb8, 0x04, 0x47, 0xfd, 0x12, 0xb4, 0xda, 0x12, 0xa4, 0xb0, 0xdf, 0xbc, 0x74, 0xf6,
	0x3e, 0xef, 0x29, 0xec, 0x5c, 0x61, 0x88, 0x75, 0x40, 0x9a, 0x8f, 0xde, 0x05, 0x52, 0x0d, 0xca,
	0xb7, 0xbe, 0x83, 0x1d, 0xa5, 0x81, 0x45, 0x54, 0xdd, 0x7a, 0x00, 0xe3, 0x1c, 0xa0, 0x5c, 0x15,
	0x56, 0xc6, 0x8f, 0x72, 0xa8, 0x71, 0xa9, 0x1c, 0xd9, 0x08, 0xb4, 0xd4, 0x72, 0xc1, 0x55, 0xdd,
	0xab, 0x69, 0xca, 0xba, 0xc7, 0x2b, 0x9d, 0xc2, 0xf6, 0x8d, 0x78, 0x75, 0xfa, 0x77, 0x08, 0xa6,
	0x0a, 0x20, 0xe7, 0x30, 0xa9, 0x68, 0x82, 0x4c, 0x59, 0x7b, 0xb6, 0xb8, 0xbb, 0xac, 0x6b, 0x94,
	0x5c, 0xc0, 0x76, 0x29, 0xed, 0x30, 0x09, 0x91, 0xec, 0xb1, 0xae, 0xe1, 0xe1, 0xee, 0x77, 0x8f,
	0x00, 0xf2, 0xb1, 0x18, 0x36, 0x35, 0x39, 0x92, 0x63, 0xd6, 0xa3, 0x6f, 0xf7, 0x84, 0xf5, 0x6a,
	0xf8, 0x0c, 0xa0, 0xc4, 0x8e, 0x10, 0xd6, 0x92, 0xab, 0x3b, 0x65, 0x1d, 0x5c, 0xbe, 0x81, 0xed,
	0x7a, 0x47, 0xc9, 0x3e, 0xeb, 0xe4, 0xd2, 0x3d, 0x60, 0xdd, 0xad, 0x57, 0x27, 0x97, 0x5d, 0x25,
	0x84, 0xb5, 0x38, 0x70, 0xa7, 0xac, 0xdd, 0x76, 0xb5, 0xad, 0xec, 0x17, 0x21, 0xac, 0xc5, 0x80,
	0x3b, 0x65, 0xed, 0x86, 0x5e, 0x5a, 0x9f, 0x4d, 0xf6, 0x3a, 0xb9, 0xbb, 0xb3, 0xf4, 0xff, 0xf2,
	0xe5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x5e, 0xcc, 0x1b, 0x3d, 0x07, 0x00, 0x00,
}
