// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: task.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Task service

type TaskService interface {
	GetTask(ctx context.Context, in *GetGroupRequest, opts ...client.CallOption) (*GetGroupResponse, error)
}

type taskService struct {
	c    client.Client
	name string
}

func NewTaskService(name string, c client.Client) TaskService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "task"
	}
	return &taskService{
		c:    c,
		name: name,
	}
}

func (c *taskService) GetTask(ctx context.Context, in *GetGroupRequest, opts ...client.CallOption) (*GetGroupResponse, error) {
	req := c.c.NewRequest(c.name, "Task.GetTask", in)
	out := new(GetGroupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Task service

type TaskHandler interface {
	GetTask(context.Context, *GetGroupRequest, *GetGroupResponse) error
}

func RegisterTaskHandler(s server.Server, hdlr TaskHandler, opts ...server.HandlerOption) error {
	type task interface {
		GetTask(ctx context.Context, in *GetGroupRequest, out *GetGroupResponse) error
	}
	type Task struct {
		task
	}
	h := &taskHandler{hdlr}
	return s.Handle(s.NewHandler(&Task{h}, opts...))
}

type taskHandler struct {
	TaskHandler
}

func (h *taskHandler) GetTask(ctx context.Context, in *GetGroupRequest, out *GetGroupResponse) error {
	return h.TaskHandler.GetTask(ctx, in, out)
}
